name: Update Dependencies

env:
  # For using the GitHub CLI:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # The branch to commit updates to
  BRANCH_NAME: update-deps

on:
  push:
    branches:
      - main
  # Run every day at midnight UTC
  # schedule:
  #   - cron: "52 * * * *"

jobs:
  update_deps:
    if: github.repository_owner == 'meganesu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all branches when checking out the repo
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "Check out branch"
        run: |
          # Check if a branch already exists with the specified BRANCH_NAME.
          CHECK_BRANCH_OUTPUT=$(git show-ref "refs/heads/${BRANCH_NAME}" | wc -l )
          # Strip the spaces from CHECK_BRANCHES_OUTPUT.
          # Will be set to 1 if a matching branch is found, or 0 otherwise.
          DOES_BRANCH_EXIST=${CHECK_BRANCH_OUTPUT// }

          # If it does, check it out
          if [ $DOES_BRANCH_EXIST = 1 ]
          then
            echo "Checking out existing branch: ${BRANCH_NAME}"
            git checkout $BRANCH_NAME
          # If it doesn't, check out a new branch with that name
          else
            echo "Checking out a new branch: ${BRANCH_NAME}"
            git checkout -b $BRANCH_NAME
          fi
      - name: "npm install"
        run: |
          npm install
          node utils/install-final-dir.js
      - name: "npm update"
        run: node utils/update-deps.js
      - name: "Commit & push changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: updated dependencies"
          git push --set-upstream origin update-deps
      - run: gh pr create --fill
